### ISSUE TITLE
[Bug]: Invalid Notion Token error

### ISSUE THREAD

**Issue by damshoe** [vzhd1701/csv2notion#28]
### csv2notion version

0.3.7

### What OS are you using?

MacOS

### OS Version / Linux distribution

Ventura 13.2.1

### Bug description

For quite some time I've been using csv2notion without any issues.

Suddenly (starting May2) I started receiving `CRITICAL: Invalid Notion token` error message whenever I try to import my file. This started happening with the token that I previously used without any issue.

I've tried generating new tokens, with different browsers and tried running script on different devices - without any success. The package is installed via homebrew, so I tried updating it - also no help at all, just stuck on the same error for few days already.

I use Google login to log in to Notion, so not sure if that affects it somehow, but the way I log in hasn't changed since I started using csv2notion. Tried to find anyone with the issue that I face but I see posts on Reddit over a year old that actually don't apply anymore.

Am I just out of luck or there actually is an issue?

### Log excerpt

```shell
csv2notion --token **mytokenhere** --url "myurlhere" import.csv

INFO: Validating CSV & Notion DB schema
CRITICAL: Invalid Notion token
```

**Comment by vzhd1701** [comment]
This should be fixed now. Please check out the new version.

**Comment by damshoe** [comment]
Homebrew package still not updated but managed to install using poetry. It's working perfectly now.

Thank you for the quick update.

**Comment by vzhd1701** [comment]
Homebrew tap is updated now.
